### ISSUE TITLE
GitLabизируемся

### ISSUE THREAD

**Issue by nott** [minskpython/minskpython.github.io#1]
Сказ о том как одна компания в поисках простого инструмента для автоматизации разработки (проверки качества, тестирования и сборки артефактов) решила отказаться от связки GitHub+Jenkins в пользу GitLab. Поговорим о том, что у них получилось, почему это просто и почему вы тоже захотите сделать подобное у себя (но это не точно).

*Nikita Grishko*

**Comment by Gr1N** [comment]
Ребят, давайте планировать мой доклад на январь, если там что-то будет. И тема доклада точно не `aiohttp`, я позже поправлю

**Comment by Gr1N** [comment]
Обновил заголовок и описание.

**Comment by Gr1N** [comment]
Слайды тут: https://github.com/Gr1N/presentations/tree/master/2018-03-28_gitlabизируемся

**Comment by Gr1N** [comment]
https://www.youtube.com/watch?v=QhdggHKnVtk
