### ISSUE TITLE
Сравнение производительности. Преимущества и подводные камни при переходе с синхронного фреймворка на асинхронный.

### ISSUE THREAD

**Issue by nott** [minskpython/minskpython.github.io#10]
*Юлия Темушева*

**Comment by shurph** [comment]
Выступление состоялось 14.11.2017. Видео опубликовано: 13 дек. 2017 г.
Видео: https://www.youtube.com/watch?v=ajVOD6JeCko&list=PLjiAaL1HtGPalbm2NI4ZTyGQgisC2l9ci&index=1
