### ISSUE TITLE
Тест, который спасет твой вечер

### ISSUE THREAD

**Issue by nott** [minskpython/minskpython.github.io#11]
*Иван Стяжкин*
https://gitpitch.com/inesusvet/tests-talk

**Comment by davojta** [comment]
А видео будет? ) Вопросы особенно интересны )

**Comment by nott** [comment]
Видео будет.

cc @ttsygan

**Comment by ttsygan** [comment]
Ну так принимай, @nott  :)
https://www.youtube.com/watch?v=0SdePcSXeKk

**Comment by shurph** [comment]
Выступление состоялось 14.11.2017 . Видео опубликовано: 13 дек. 2017 г.
Видео: https://www.youtube.com/watch?v=0SdePcSXeKk&list=PLjiAaL1HtGPalbm2NI4ZTyGQgisC2l9ci&index=3
