### ISSUE TITLE
Selenium то, selenium сё

### ISSUE THREAD

**Issue by rtut** [minskpython/minskpython.github.io#14]
Selenium настройка.
Selenium тестирование.
Selenium скраппинг.

**Comment by shurph** [comment]
Выступление состоялось 28.03.2018. Видео опубликовано:  1 сент. 2018 г.
Видео: https://www.youtube.com/watch?v=wC3cuAxiKOA&list=PLjiAaL1HtGPb8U9f0QPOQXcbJaR8atAPR&index=2
