### ISSUE TITLE
Worship you code review

### ISSUE THREAD

**Issue by MrLokans** [minskpython/minskpython.github.io#15]
This talk is about conducting code reviews, common pitfalls, gotchas and recommendations.

**Comment by nott** [comment]
@MrLokans 

у нас есть слоты на май и июнь

**Comment by MrLokans** [comment]
@nott, я за май, что мне необходимо дальше сделать?

**Comment by nott** [comment]
@MrLokans отписал вчера на почту

**Comment by shurph** [comment]
Выступление состоялось 30.05.2018.
Видео: https://www.youtube.com/watch?v=qADYWuy9IDg&list=PLjiAaL1HtGPb8U9f0QPOQXcbJaR8atAPR
