### ISSUE TITLE
Telegram бот на Python своими руками

### ISSUE THREAD

**Issue by umax** [minskpython/minskpython.github.io#16]
Могу рассказать про возможности ботов в Telegram, особенности API, почему для написания ботов не нужны доп. библиотеки и фреймворки, ответить на любые вопросы относительно Telegram API.

Примерный план:
- беглый обзор Telegram API;
- библиотеки и фреймворки не нужны;
- как реализовать сложный сценарий взаимодействия с пользователем;
- пример бесплатного деплоя;
- что технически может бот. Вопросы от аудитории.

Примеры моих ботов:
- http://damavikbot.by
- http://splittybot.me

**Comment by krasoffski** [comment]
Будет очень здорово послушать про реальный опыт (и ботов сложнее "Hello World!"). 
Еще если есть смысл, упомянуть про сихронный и асинхронный подход в написании ботов что выбрать и когда.
Большое спасибо!

**Comment by nott** [comment]
@umax 

что думаешь про май или июнь?

**Comment by umax** [comment]
Могу в мае или в июне :)

**Comment by Gr1N** [comment]
https://www.youtube.com/watch?v=8Jltggv8mN4
