### ISSUE TITLE
typing. typing? typing!

### ISSUE THREAD

**Issue by Gr1N** [minskpython/minskpython.github.io#17]
Не так давно в Python завезли `import typing`: кто-то его использует, кто-то его не признает и даже ненавидит, но мало кто задумывается, что это не только возможность описать типы с их последующим анализом посредством `mypy`. В этом докладе мы попробуем взглянуть на `typing` под другим углом и добавим ему пару плюсов в пользу использования на вашем проекте.

**Comment by Gr1N** [comment]
Готов вписаться в июнь

**Comment by shurph** [comment]
Выступление состоялось 13.11.2018.
Видео: https://www.youtube.com/watch?v=k03RQqdJADU&list=PLjiAaL1HtGPb8U9f0QPOQXcbJaR8atAPR&index=16
