### ISSUE TITLE
Управляем зависимостями на проекте

### ISSUE THREAD

**Issue by Gr1N** [minskpython/minskpython.github.io#18]
Пока кратко: поговорим об управлении зависимостями на нашем проекте.
Ключевые слова: `pip`, `pip-tools`, `pyenv`, `pipenv`.

**Comment by shurph** [comment]
Было бы инетерсно послушать опыт других людей.

**Comment by Gr1N** [comment]
https://www.youtube.com/watch?v=YErAfIWC0wk
