### ISSUE TITLE
Integration vs Composition

### ISSUE THREAD

**Issue by inesusvet** [minskpython/minskpython.github.io#19]
In this talk, I want to discuss two different approaches to development tasks:
- Putting something inside of something aka _Integration_
- Wrapping something around something else aka _Composition_

This talk will cover such topics as #testability #decomposition #complexity

Inspired by a [simple task](https://www.codewars.com/kata/string-transformer) and my bright students

**Comment by inesusvet** [comment]
> # Integration vs Composition
> Положим у Вас есть на руках MVP. Теперь нужно его развить в продукт, приносящий доход его создателям.
> Я хочу обсудить два подхода к развитию Вашего ПО:
> - Помещать новую логику внутрь существующей логики (иногда это называют “интегрировать”)
> - Оборачивать новую логику вокруг существующей логики (кое-кто это называет “компоновать”)
>
> В этом докладе будут затронуты такие темы как #testability #decomposition #complexity #dependency

**Comment by inesusvet** [comment]
Slides https://gitpitch.com/inesusvet/complexity-talk

**Comment by Gr1N** [comment]
https://www.youtube.com/watch?v=Ytbm1BfDGRg
