### ISSUE TITLE
Data pipelines and Python.

### ISSUE THREAD

**Issue by electronick1** [minskpython/minskpython.github.io#21]
Такие термины как ETL и Data pipelines все более популярны с развитием Data science и ML.
И в первую очередь это касается Python, так как он один из главных лидеров в этой области.
В докладе речь пойдет о истории Data pipelines, о том как они помогают Doist решать сложные ML и ETL задачи, и о том куда это все движется.

**Comment by karelin** [comment]
Похожий (возможно очень отдаленно) пакет: http://selinon.readthedocs.io/en/latest/

**Comment by shurph** [comment]
Выступление состоялось 12.12.2018.
Видео: https://www.youtube.com/watch?v=BOJUiEN7eXY&list=PLjiAaL1HtGPb8U9f0QPOQXcbJaR8atAPR&index=20
