### ISSUE TITLE
Let's typehint

### ISSUE THREAD

**Issue by quozd** [minskpython/minskpython.github.io#31]
В этом докладе я хотел бы обсудить как, когда и зачем применять type hints, какие плюсы и минусы ожидают, пройтись по частым ошибкам, проблемам и их решению, показать некоторые важные вещи, облегчающие жизнь с type hints.

Доклад рассчитан на две категории слушателей:
- тех, кто обдумывает или планирует внедрение type hints на своем проекте и хочет узнать, что их ждет
-  тех, кто уже активно использует type hints

ЗЫ. Доклад уже готов и обкатан на внутрикорпоративном ивенте.

**Comment by MIKSby** [comment]
Очень интересная тема

**Comment by shurph** [comment]
Выступление состоялось 19.03.2019. Видео опубликовано: 26 мар. 2019 г.
Видео: https://www.youtube.com/watch?v=QDy2ZFb9HvQ&list=PLjiAaL1HtGPaMPlrZGCDzUCTsVAyTbHJ4&index=1
