### ISSUE TITLE
Stairs.

### ISSUE THREAD

**Issue by electronick1** [minskpython/minskpython.github.io#33]
В своем докладе я хочу сфокусироваться на задачах которые могут решать data-pipelines, показать сильные и слабые стороны данного подхода, рассказать как я попытался устранить эти слабые стороны в библиотеке stairs и показать почему эта концепция заслуживает внимания python разработчика

Stairs - это framework который позволяет максимально легко создавать data pipelines различной сложности, и выполнять параллельные распределенные вычисления.

Одна из основных идей заключается в том, чтобы сфокусировать работу программиста только на обработке данных, а все процессы связанные с распределенными вычислениями можно будет доверить stairs. Кроме распределенности stairs позволяет легко понимать и представлять весь поток обработки данных - это особенно важно когда тебе нужно протестировать большое количество подходов (например при обучении ML моделей)

**Comment by shurph** [comment]
Выступление состоялось 19.03.2019. Видео опубликовано: 26 мар. 2019 г.
Видео: https://www.youtube.com/watch?v=8hazPUWTK94&list=PLjiAaL1HtGPaMPlrZGCDzUCTsVAyTbHJ4&index=2
