### ISSUE TITLE
Python + Prometheus = ?

### ISSUE THREAD

**Issue by Gr1N** [minskpython/minskpython.github.io#39]
Все мы так или иначе пишем сервисы и хотим понимать насколько хорошо они выполняют поставленные задачи и обслуживают пользователей. Но для понимания нам необходимо получать от этих сервисов телеметрию (кол-во входящих запопросов, сколько из них завершились успешно, сколько времени заняло их выполнение и т.д.), а также где-то эту телеметрию хранить и иметь возможность с ней взаимодействовать для дальнейшего анализа. Зачастую, для решения данной задачи выбирают [Prometheus](https://prometheus.io/docs/prometheus/latest/getting_started/) являющегося на данный момент лидером среди open-source решений для мониторинга.

В рамках данного доклада мы поговорим о том, как подружить сервисы написанные на Python c Prometheus, какие есть подводные камни, почему pull модеть может плохо работать в случае Python сервисов и как собрать для себя небольшую, но уютную и рабочую инфраструктуру для мониторинга ваших сервисов.

**Comment by shurph** [comment]
Выступление состоялось 23.04.2019.
Видео: https://www.youtube.com/watch?v=K97fbAXy83A&list=PLjiAaL1HtGPaMPlrZGCDzUCTsVAyTbHJ4
