### ISSUE TITLE
Refactoring: a small story

### ISSUE THREAD

**Issue by inesusvet** [minskpython/minskpython.github.io#40]
I suppose you know what _Refactoring_ is and I have no goal to rephrase [Martin Fowler’s book](https://www.martinfowler.com/books/refactoring.html). We may have a discussion on some of the following meta-questions:
- Really, why do you need it in the first place?
- So, when you should use it? When you shouldn’t?
- But what actually you will change?
- And how to actually deliver your changes to production?

**Comment by pavelpy** [comment]
Video https://youtu.be/QN7WVwuoh3E
