### ISSUE TITLE
Как я студентов питону учил.

### ISSUE THREAD

**Issue by demidov91** [minskpython/minskpython.github.io#43]
Расширинный lightning talk: light talk. За минут 15-20 рассказать о выводах и вопросах, которые остались без ответа, после одного семестра приёма лабораторных работ у студентов Информатики в БГУИР. Какие-то мысли о продвижении митапов среди заинтересованных в этом студентов. 
В конце проводил анкетирование, поэтому будет с графиками :)

**Comment by shurph** [comment]
Выступление состоялось 14.09.2019.
Видео: https://www.youtube.com/watch?v=RCISpSNoPmk&list=PLjiAaL1HtGPaMPlrZGCDzUCTsVAyTbHJ4&index=11
