### ISSUE TITLE
Streamsets

### ISSUE THREAD

**Issue by shushkaden** [minskpython/minskpython.github.io#46]
Испокон веков наши предки перекладывали джейсоны из одной апишки в другую.
Мы чтим их традиции и занимаемся тем же самым, изобретая всё новые и новые велосипеды в виде микросервисов.

Но настали смутные времена! Все те идеалы, которые так доблестно отстаивали наши родичи, под угрозой.

Ходят слухи, что наш любимый копипаст БейзДжейсонКлиент-ов из микросервиса в микросервис можно забыть, а рутинные задачи выполнять не выходя из браузера.
Глупости конечно это всё. Или нет?!

Покажу что такое streamsets, и как с помощью этой штуки можно делать backend задачи.

**Comment by shushkaden** [comment]
@shurph, привет. Добавим в Talk proposal?

**Comment by shurph** [comment]
Выступление состоялось 14.09.2019.
Видео: https://www.youtube.com/watch?v=1Ui1MByvFM0&list=PLjiAaL1HtGPaMPlrZGCDzUCTsVAyTbHJ4&index=9
