### ISSUE TITLE
Стартуем новый проект - что нам нужно

### ISSUE THREAD

**Issue by MrLokans** [minskpython/minskpython.github.io#47]
Как много раз вы приходили на новый проект и задумывались - "почему все так плохо?".
Я постараюсь описать практики и подходы, про которые разработчики зачастую забывают при старте новых проектов и, в результате, может получиться "какашка", которую нет никакой радости поддерживать и разрабатывать: SDLC-практики, работа с документацией и требованиями

Кому может быть полезен доклад: максимально широкой аудитории, в частности начинающим лидам и архитекторам

Presentation: https://docs.google.com/presentation/d/1QpVQXjDsaa32JIIPgPuQVUZIEZypnbG0JAgpFk3mPe4/edit?usp=drivesdk

#sdlc #architecture #design #teamleading #leading

**Comment by shurph** [comment]
Выступление состоялось 14.09.2019.
Видео: https://www.youtube.com/watch?v=iXxf8Gs8f-o&list=PLjiAaL1HtGPaMPlrZGCDzUCTsVAyTbHJ4&index=12
