### ISSUE TITLE
Не любите type hinting? Вы просто не умеете его готовить!

### ISSUE THREAD

**Issue by TBoris** [minskpython/minskpython.github.io#48]
В python версии 3.5 завезли модуль typing и рассказали про PEP 484.
В следующей версии работу с типами облегчил PEP 526. 
Ещё чуточку удобней и быстрей стало работать с типами в python 3.7.
Как мы видим, Гвидо с товарищами не сдаётся и как бы шепчет: «хочешь ещё этих постепенных питонячьих типизаций?», и продолжает пилить mypy — инструмент для проверки типов в вашем коде.
В докладе я расскажу, как не только по-модному расставить типы и поссориться с коллегами, не желающими «превращать мой Python в эту вашу Java», но и действительно извлечь из него пользу.
Для этого нужно всего лишь...

**Comment by shurph** [comment]
Выступление состоялось 14.09.2019.
Видео: https://www.youtube.com/watch?v=kyVspqEcs-s&list=PLjiAaL1HtGPaMPlrZGCDzUCTsVAyTbHJ4&index=10
