### ISSUE TITLE
ASGI - не еще один gateway

### ISSUE THREAD

**Issue by TheML9I** [minskpython/minskpython.github.io#49]
В докладе рассмотрю основные концепции ASGI, вопросы применимости. 
Насколько всё production-ready. Стоит ли начинать его использовать уже сгодня.

**Comment by shurph** [comment]
Выступление состоялось 28.11.2019.

Видео: https://www.youtube.com/watch?v=HGcv9WAKkPM&list=PLjiAaL1HtGPaMPlrZGCDzUCTsVAyTbHJ4&index=18
