### ISSUE TITLE
celery decorator app.taskcls: пишем код так, чтобы он не растекался

### ISSUE THREAD

**Issue by kai3341** [minskpython/minskpython.github.io#50]
Это доклад о будущей возможности celery. Идея -- применить всю мощь ООП для задач celery
Больше подробностей на хабре: https://habr.com/ru/post/470547/

**Comment by shurph** [comment]
Выступление состоялось 28.11.2019.
Видео: https://www.youtube.com/watch?v=0oLaikb5BdE
