### ISSUE TITLE
Эволюция упаковки и дистрибьюции в Python

### ISSUE THREAD

**Issue by nott** [minskpython/minskpython.github.io#6]
*Дмитрий Назаров*

**Comment by shurph** [comment]
Выступление состоялось 14.12.2017. Видео опубликовано: 10 июл. 2018 г.
Видео: https://www.youtube.com/watch?v=FJxlsXqkxMQ&list=PLjiAaL1HtGPalbm2NI4ZTyGQgisC2l9ci&index=5
